---
install:
  - sudo snap install hugo

script:
  - make docs

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_DEPLOY_TOKEN
  keep_history: true
  local_dir: docs
  on:
    branch: travis_test
